### PR TITLE
draft of feature list

### PR DESCRIPTION
**Pull request by melchiar**
added draft of features list with basic css

### CODE REVIEW

**Comment by asturur** [comment]
```jsx
      <div id="featuresList">
        <div className="col">
          <h2>Power</h2>
          <p>A powerful feature set, including rich text formatting, complex shapes, svg import & export, groups, filters, animations, and much more!</p>
        </div>
        <div className="col">
          <h2>Performance</h2>
          <p>Advanced object caching and a WebGL-powered filter engine ensures fast and consistent performance even for highly complex canvases.</p>
        </div>
        <div className="col">
          <h2>Simplicity</h2>
          <p>A simple object-oriented structure for easy object creation, manipulation, and serialization.</p>
        </div>
        <div className="col">
          <h2>Flexibility</h2>
          <p>Open-source and fully extensible, with a modular design and custom build support.</p>
        </div>
      </div>
```

**Comment by asturur** [comment]
https://github.com/fabricjs/fabricjs.github.io/blob/development/src/components/Features/Features.jsx#L5

**Comment by asturur** [comment]
Sorry had to solve the conflict, saved your list in the comment

**Comment by ShaMan123** [comment]
> ```jsx
>       <div id="featuresList">
>         <div className="col">
>           <h2>Power</h2>
>           <p>A powerful feature set, including rich text formatting, complex shapes, svg import & export, groups, filters, animations, and much more!</p>
>         </div>
>         <div className="col">
>           <h2>Performance</h2>
>           <p>Advanced object caching and a WebGL-powered filter engine ensures fast and consistent performance even for highly complex canvases.</p>
>         </div>
>         <div className="col">
>           <h2>Simplicity</h2>
>           <p>A simple object-oriented structure for easy object creation, manipulation, and serialization.</p>
>         </div>
>         <div className="col">
>           <h2>Flexibility</h2>
>           <p>Open-source and fully extensible, with a modular design and custom build support.</p>
>         </div>
>       </div>
> ```

This is noy good enough IMO
Needs to be more precise, less text, more bullets.
Not use "object oriented" and such. It has an outdated feel.

**Comment by ShaMan123** [comment]
Things like
- powerful
- customizable
- API

Sexy words
What about the logo?

**Comment by asturur** [comment]
> Things like
> 
> * powerful
> * customizable
> * API
> 
> Sexy words What about the logo?

There is no rush, everyone adds what he thinks is good and representative, then we pick up the best from all.

**Comment by asturur** [comment]
Logo i like the old more, i m kind of used to it, other than i have  bunch of stickers around, that i also shipped around the world to who asked ( and seems like no one received them )

**Comment by melchiar** [comment]
> Logo i like the old more, i m kind of used to it, other than i have bunch of stickers around, that i also shipped around the world to who asked ( and seems like no one received them )

I also prefer the old logo

**Comment by ShaMan123** [comment]
If we are trying to sell it I would think of sentences such as
"built for..."
"Visuals, interaction and ease of customization"
And I would try to link each feature to a live demo that demonstrates that, when we get to that.

**Comment by asturur** [comment]
Yes i agree we can finetune it.
Let's just put all the content in to see how much space things take in the layout and how look in the mobile phone.
A vague idea of what we want to write is still better than `lorem ipsus dolor` repeated everywhere.

**Comment by asturur** [comment]
This thing is online on the link https://fabricjs.github.io and is not official or nothing, but if we want to have this ready at some point we need to work on it.
The old website is considered unusable from me too

**Pull request merged**
