### PR TITLE
Added demo pages

### LINKED ISSUE #18: Add directories & markdown files for demos
Based off the [current website](http://fabricjs.com) write out content for each of the demo pages.
Directories for the demo pages are under [src/pages/demos directory](https://github.com/fabricjs/fabricjs.github.io/tree/development/src/pages/demo) and one can even refer some content which is already there 🤗 before writing out another demo page

In the markdown, include the **title**, **description** and the **thumbnail** as front-matter

### PR DESCRIPTION
**Pull request by nimworks**
Closes #18

@asturur Each commit to this PR would correspond to new demo-page being added and thus would help you track which pages have already been added! As suggested by you, I am adding newest first as listed in the [current website repo](https://github.com/fabricjs/fabricjs.com/tree/gh-pages/posts/demos/_posts) 🤗

I'll add more subsequent commits for remaining pages which would be reflected in this PR thread

### CODE REVIEW

**Comment by asturur** [comment]
i see you are working on a fork, so i ll start a new PR.

**Comment by asturur** [comment]
i see that conversion to codepen is mostly mandatory.

**Comment by asturur** [comment]
I did not have time to work on it, at all. I'm sorry you have to do the heavy lifting here.
We have enough pages ( all? ) let's just merge those so you can concentrate on design, i can take care of content in spare time ( when i have some )

**Comment by nimworks** [comment]
> I did not have time to work on it, at all. I'm sorry you have to do the heavy lifting here

Ohh please don't b 😇. It's very much fine! On the positive side, I actually got to c and understand each of the demos 🤗

> We have enough pages ( all? )

Some more pages are yet to be added! I was figuring out how we are to load images in the CodePens coz for some of the demos (lanczos-webgl), including it as data-url makes the server complain abt data  being too lengthy fetch or something on those lines! _(I'd share the exact error screen-shot later)_

Yes, for now this many demos would suffice as the base!

**Pull request merged**
