### PR TITLE
style team + add github links

### PR DESCRIPTION
**Pull request by ShaMan123**
first merge #69

### CODE REVIEW

**Comment by asturur** [comment]
i can merge 69 probably in a bit, just adding one or two extra demo and then opening an issue for whoever wants to adds them. i ll work on api docs and general introduction

**Comment by asturur** [comment]
Do you think the sponsor button can by styled? it does not blend with the page

**Comment by asturur** [comment]
i ll try that

**Comment by ShaMan123** [comment]
You can dump the shield in favor of any other button/a

**Comment by asturur** [comment]
image


i'll go with this for now.
At least is the original icon and it follows our style with variables

```css
.team-member .sponsor-button {
  display: flex;
  align-items: center;
  border-radius: var(--border-radius-normal);
  border: 2px solid var(--primary-color);
  max-width: 130px;
  justify-content: center;
}

.team-member .sponsor-button svg {
  margin-right: 16px;
  stroke: var(--primary-color);
  fill: var(--primary-color);
}

```

**Pull request merged**
