### PR TITLE
fix(): demos code

### PR DESCRIPTION
**Pull request by ShaMan123**
Now supports a js file
I want to rename the file code.js => index.js but I didn't to keep the diff sane

### CODE REVIEW

**Review by ShaMan123 — COMMENTED** [review]
ready

**Review by ShaMan123 — COMMENTED** [review]
ready

**Comment by asturur** [comment]
I don't want to think about this now, there are too many changes and i m not sure every is needed.
For example now the code editor is part of the demo template that limit in flexibility on what you can do, and is unclear how i export 2 functions to assign to two different editors.
This is not urgent imho and we can see how to keep functions in the moment we have a larger amount of demos available, this is why i rushed to fix it with the const string, because for now is not necessary to put time on it.

Is ok to write the code in a function while developing it and then change it to a const when we are done, we can also just do that at runtime and live the functions.

**Comment by ShaMan123** [comment]
I disagree, for me is a pain

**Comment by ShaMan123** [comment]
but anyways I won't be working on demos for a while and I guess you will finish them

**Comment by asturur** [comment]
> I disagree, for me is a pain

i opened a pr, i couldn't fix it, i wrote that we know we didn't like it, and that it wasn't important to fix it immediately.

Rushing to counter my pr because you don't like the const string while i m still working on demos is not useful.

at the end we will have a js file

**Pull request closed without merging**
